#! /bin/sh

SCREEN_NUMBER=3
laptop_mon="DP-4"
left_screen="HDMI-0"
right_screen="DP-0"

echo "screen number is $SCREEN_NUMBER"

sxhkd &

bspc config border_width 2
bspc config window_gap 10

bspc config split_ratio 0.50
bspc config borderless_monocle true
bspc config gapless_monocle true

# bspc rule -a Gimp desktop='^8' state=floating follow=on
bspc rule -a Chromium desktop='^1'
bspc rule -a mplayer2 state=floating
bspc rule -a Kupfer.py focus=on
bspc rule -a Screenkey manage=off

if [ $SCREEN_NUMBER -eq 3 ]; then
  xrandr --output $left_screen --primary --mode 2560x1440 --rotate normal --output $right_screen --rotate normal --right-of $left_screen --output $laptop_mon --rotate normal --below $right_screen
  bspc monitor $left_screen -d 1 2 3 4 5
  bspc monitor $right_screen -d 6 7 8 9
  bspc monitor $laptop_mon -d 10 11
fi

if [ $SCREEN_NUMBER -eq 1 ]; then
  xrandr --output $laptop_mon --primary --mode 2560x1440 --rotate normal
  bspc monitor $laptop_mon -d 1 2 3 4 5 6 7 8 9 10
fi

# if xrandr -q | grep 'HDMI-0 connected' >/dev/null 2>&1; then
# if [[ $(xrandr -q | grep "HDMI-1-0 connected") ]]; then
# xrandr --output HDMI-0 --primary --mode 2560x1440 --rotate normal --output DP-4 --rotate normal --right-of HDMI-0
# else
#   xrandr --output eDP-1 --primary --mode 1920x1080 --rotate normal
#   bspc monitor -d 1 2 3 4 5 6 7 8 9
#   feh --bg-fill ~/Pictures/wow.jpg
#   ~/.config/polybar/single_launch.sh &

picom -b &
# feh --bg-fill ~/Pictures/onyxia.png
bash /home/scott/.config/bspwm/background_picker.bash
~/.config/polybar/single_launch.sh &
