#! /bin/sh

sxhkd &

if [[ $(xrandr -q | grep 'HDMI-0 connected') ]]; then
  xrandr --output HDMI-0 --primary --mode 1920x1080 --rotate normal --output DVI-D-0 --mode 1920x1080 --rotate normal --right-of HDMI-0
fi

bspc monitor HDMI-0 -d 1 2 3 4 5 
bspc monitor DVI-D-0 -d 6 7 8 9 10 

bspc config border_width         2
bspc config window_gap          12

bspc config split_ratio          0.52
bspc config borderless_monocle   true
bspc config gapless_monocle      true

bspc rule -a Gimp desktop='^8' state=floating follow=on
bspc rule -a Chromium desktop='^2'
bspc rule -a mplayer2 state=floating
bspc rule -a Kupfer.py focus=on
bspc rule -a Screenkey manage=off

xwallpaper --zoom ~/Downloads/754912.png
tint2
