#! /bin/sh

sxhkd &

bspc config border_width         2
bspc config window_gap          10

bspc config split_ratio          0.50
bspc config borderless_monocle   true
bspc config gapless_monocle      true

bspc rule -a Gimp desktop='^8' state=floating follow=on
bspc rule -a Chromium desktop='^2'
bspc rule -a mplayer2 state=floating
bspc rule -a Kupfer.py focus=on
bspc rule -a Screenkey manage=off

# if xrandr -q | grep 'HDMI-0 connected' >/dev/null 2>&1; then
# if [[ $(xrandr -q | grep "HDMI-1-0 connected") ]]; then
xrandr --output HDMI-0 --primary --mode 2560x1440 --rotate normal --output DP-2 --mode 1920x1080 --rotate normal --right-of HDMI-0 
bspc monitor HDMI-0 -d 1 2 3 4 5
bspc monitor DP-2 -d 6 7 8 9 

# else 
#   xrandr --output eDP-1 --primary --mode 1920x1080 --rotate normal 
#   bspc monitor -d 1 2 3 4 5 6 7 8 9
#   feh --bg-fill ~/Pictures/wow.jpg
#   ~/.config/polybar/single_launch.sh &

picom -b &
feh --bg-fill ~/Pictures/Wallpapers/Misty_Mountains.jpg
~/.config/polybar/single_launch.sh &

