require "user.options"
require "user.keymaps"
require "user.plugins"
require "user.colourschemes.gruvbox"
require "user.auto_complete"
require "user.lsp"
require "user.telescope"
require "user.treesitter"
